version: "3.9"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "plugin-store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db: